"""
Textbook glossary: key concepts from Mankiw, Principles of Microeconomics /
Brief Principles of Macroeconomics (10th ed.), chapters 1-22, plus the
vocabulary used around them in the chapter 1 & 2 slides.

Every entry is written in our own words as a drop-in plain phrase, a short
meaning, and an everyday example. Same format as glossary.py.
"""

from glossary import T

TEXTBOOK_TERMS = [
    # ------------------------------------------------ ch1: ten principles
    T("economics", "economics",
      "The study of how people, businesses, and countries decide what to do with limited time, money, and stuff.",
      "Why a student picks a job over a nap, or why a country builds roads instead of tanks.",
      keep=True),
    T("trade-off", "a give-and-take choice",
      "Getting more of one thing means getting less of something else.",
      "An extra hour at work is an hour less with friends.",
      ["trade-offs", "tradeoff", "tradeoffs", "trade off", "trade offs"],
      plural="give-and-take choices"),
    T("no free lunch", "nothing is truly free",
      "Every choice costs something, even if no money changes hands, because you gave up the alternative.",
      "A 'free' concert still costs you the evening you could have spent elsewhere.",
      ["there is no free lunch", "there's no free lunch", "there is no such thing as a free lunch"]),
    T("efficiency", "getting the most out of what you have",
      "Squeezing the most value out of limited resources, with nothing wasted. The 'size of the pie'.",
      "A kitchen where every burner is in use and no food is thrown away.",
      ["economic efficiency", "allocative efficiency"]),
    T("inefficiency", "wasting what you have",
      "Producing less than you could from your resources, or using them on the wrong things.",
      "A factory with half its machines idle.",
      ["inefficiencies"]),
    T("equality", "how evenly wealth is shared",
      "How evenly the economy's benefits are spread across people. The 'slicing of the pie'.",
      "Two roommates splitting groceries 50/50 rather than one eating most of it.",
      ["economic equality"]),
    T("rational people", "people who weigh costs and benefits",
      "The textbook assumption that people do the best they can for themselves given their options, comparing what they gain against what they give up.",
      "Someone who checks whether the drive to a cheaper store is worth the gas.",
      ["rational person", "rational decision makers", "rational decision-makers", "rationally"]),
    T("marginal change", "a small extra step",
      "A small tweak to what you are already doing: one more, or one less.",
      "Deciding whether to study one more hour, not whether to study at all.",
      ["marginal changes", "marginal adjustment", "marginal adjustments", "incremental change"]),
    T("think at the margin", "compare the next small step's costs and benefits",
      "Making decisions by asking whether one more unit is worth its extra cost, rather than all-or-nothing.",
      "An airline sells a last-minute seat for $50 because the extra passenger costs it almost nothing.",
      ["thinking at the margin", "thinks at the margin", "marginal thinking", "marginal analysis", "marginal decision making"]),
    T("marginal benefit", "the extra benefit from one more",
      "What you gain from a small additional amount of something.",
      "The enjoyment from a third slice of pizza.",
      ["marginal benefits"],
      plural="extra benefits from one more"),
    T("marginal cost", "the extra cost of one more",
      "What it costs to produce or get one additional unit.",
      "The dough and cheese for one more pizza, not the oven.",
      ["marginal costs"],
      plural="extra costs of one more"),
    T("market economy", "an economy run by millions of buyers and sellers",
      "An economy where businesses and households decide what to make, buy, and sell, instead of a central government planner.",
      "Restaurants open where people want to eat, not where an official assigns them.",
      ["market economies"]),
    T("centrally planned economy", "an economy run by government planners",
      "An economy where a central authority decides what gets made, how much, and who gets it.",
      "The Soviet Union deciding how many shoes each factory would produce.",
      ["central planning", "command economy", "planned economy"]),
    T("central planner", "a government official deciding what gets made",
      "Someone in government who decides what the economy should produce and who gets it, instead of leaving it to buyers and sellers.",
      "An official in Moscow in 1970 setting the number of tractors each factory must build.",
      ["central planners"],
      plural="government officials deciding what gets made"),
    T("property rights", "the legal right to own and control things",
      "The rules that let people own things and decide how they are used, backed by courts.",
      "A farmer will only plant if they know no one can legally take the harvest.",
      ["property right", "enforce property rights"]),
    T("market power", "the ability to push prices around",
      "When a single buyer or seller is big enough to influence the market price instead of just accepting it.",
      "The only gas station for 50 miles charging what it likes."),
    T("scientific method", "test ideas against evidence",
      "Coming up with a theory, then checking it against real-world data.",
      "Guessing that higher prices cut sales, then looking at sales figures to see.",
      ["the scientific method"]),
    T("economic model", "a simplified picture of how part of the economy works",
      "A diagram or equation that leaves out details to make one relationship easier to see.",
      "A subway map: not to scale, but it shows how to get around.",
      ["economic models"],
      plural="simplified pictures of how the economy works"),
    T("assumption", "a simplification taken as given",
      "Something assumed to be true to make a problem easier to think about.",
      "Pretending there are only two countries in the world to explain trade.",
      ["assumptions"],
      plural="simplifications taken as given"),

    # ------------------------------------------------ ch2: thinking like an economist
    T("circular-flow diagram", "the money-goes-round map",
      "A simple picture showing money flowing from households to businesses when they buy things, and back to households as wages and profit.",
      "You pay a cafe for coffee; the cafe pays its barista, who buys coffee somewhere else.",
      ["circular flow diagram", "circular flow", "circular-flow"]),
    T("production possibilities frontier", "the most-you-can-make curve",
      "A graph showing every combination of two things an economy could produce if it used everything it has. Points inside the curve are wasteful; points outside are impossible.",
      "A bakery with one oven can make 100 loaves, or 200 muffins, or some mix, but not both maxed out.",
      ["production possibilities frontiers", "production possibility frontier", "production possibilities curve", "ppf", "the ppf"]),
    T("positive statement", "a claim about how things are",
      "A statement about facts that could in principle be checked against evidence.",
      "'Raising the minimum wage reduces teen employment' is testable, whether or not it turns out true.",
      ["positive statements", "positive analysis", "positive economics"],
      plural="claims about how things are"),
    T("normative statement", "a claim about how things should be",
      "A statement of opinion or values that cannot be settled by evidence alone.",
      "'The government should raise the minimum wage.'",
      ["normative statements", "normative analysis", "normative economics"],
      plural="claims about how things should be"),
    T("absolute advantage", "being able to make more with the same resources",
      "Being flat-out better at producing something, using fewer inputs than someone else.",
      "A chef who can chop twice as many onions per hour as a trainee."),

    # ------------------------------------------------ ch3-4: markets, supply & demand
    T("competitive market", "a market with many buyers and many sellers",
      "A market where there are so many buyers and sellers that no single one can affect the price.",
      "Wheat farmers: there are thousands, so no one farmer can raise the price.",
      ["competitive markets", "perfectly competitive market"]),
    T("price taker", "someone who has to accept the going price",
      "A buyer or seller too small to influence the price, so they take it as given.",
      "A corn farmer selling at whatever the market pays that day.",
      ["price takers"],
      plural="people who have to accept the going price"),
    T("quantity demanded", "the amount people will buy at a given price",
      "How much of something buyers are willing and able to buy at one specific price.",
      "At $2 a scoop, the town buys 500 ice creams a day."),
    T("quantity supplied", "the amount sellers will offer at a given price",
      "How much of something sellers are willing and able to sell at one specific price.",
      "At $2 a scoop, the shops are willing to sell 300 ice creams a day."),
    T("law of demand", "people buy less when the price goes up",
      "All else equal, a higher price means people buy less, and a lower price means they buy more.",
      "Sales of strawberries jump when they go on special.",
      ["the law of demand"]),
    T("law of supply", "sellers offer more when the price goes up",
      "All else equal, a higher price means sellers are willing to produce and sell more.",
      "More people pick up ride-share shifts when surge pricing is on.",
      ["the law of supply"]),
    T("law of supply and demand", "prices settle where buying matches selling",
      "The price of anything moves to the level where the amount people want to buy equals the amount sellers want to sell.",
      "Concert tickets get pricier until exactly enough fans are willing to pay.",
      ["the law of supply and demand"]),
    T("demand schedule", "a table of prices and how much people would buy",
      "A list showing, for each price, how much buyers would purchase.",
      "$1: 800 scoops, $2: 500 scoops, $3: 200 scoops.",
      ["demand schedules"]),
    T("demand curve", "the line showing how much people buy at each price",
      "A graph of the demand schedule. It slopes down because people buy less as the price rises.",
      "Plot price against ice creams bought and you get a downhill line.",
      ["demand curves"],
      plural="lines showing how much people buy at each price"),
    T("supply schedule", "a table of prices and how much sellers would offer",
      "A list showing, for each price, how much sellers would sell.",
      "$1: 100 scoops, $2: 300 scoops, $3: 600 scoops.",
      ["supply schedules"]),
    T("supply curve", "the line showing how much sellers offer at each price",
      "A graph of the supply schedule. It slopes up because sellers offer more as the price rises.",
      "Plot price against ice creams offered and you get an uphill line.",
      ["supply curves"],
      plural="lines showing how much sellers offer at each price"),
    T("equilibrium quantity", "the amount bought and sold at the balance price",
      "How much changes hands when supply and demand are balanced.",
      "At $2, buyers want 400 and sellers offer 400, so 400 scoops are sold."),
    T("normal good", "something you buy more of when you earn more",
      "A product people buy more of as their income rises.",
      "Restaurant meals, new clothes, vacations.",
      ["normal goods"],
      plural="things you buy more of when you earn more"),
    T("inferior good", "something you buy less of when you earn more",
      "A product people buy less of as their income rises, because they can now afford something better.",
      "Instant noodles and bus tickets, once you can afford steak and a car.",
      ["inferior goods"],
      plural="things you buy less of when you earn more"),
    T("substitutes", "things you could buy instead of each other",
      "Two products where a price rise in one makes people buy more of the other.",
      "Coke and Pepsi, butter and margarine, movie tickets and streaming.",
      ["substitute goods", "substitute good", "close substitutes", "a substitute"]),
    T("complements", "things you buy together",
      "Two products where a price rise in one makes people buy less of the other, because they go together.",
      "Hot dogs and buns, printers and ink, cars and gas.",
      ["complementary goods", "complementary good", "a complement"]),
    T("perfect substitutes", "things you swap one-for-one without caring",
      "Two products a buyer treats as completely interchangeable.",
      "A $10 bill and two $5 bills."),
    T("perfect complements", "things only useful together in fixed amounts",
      "Two products that must be used together in a set ratio.",
      "Left shoes and right shoes."),

    # ------------------------------------------------ ch5: elasticity
    T("price elasticity of supply", "how much sellers change output when the price changes",
      "A measure of how strongly the amount sellers offer responds to a price change.",
      "Beachfront land: the price doubles but there is no more of it to sell.",
      ["elasticity of supply", "supply elasticity"]),
    T("income elasticity of demand", "how much buying changes when income changes",
      "A measure of how strongly purchases respond to a change in people's income.",
      "A 10% raise and you eat out 20% more: eating out is very income-sensitive.",
      ["income elasticity"]),
    T("cross-price elasticity of demand", "how much buying of one thing changes when another's price changes",
      "A measure of how the purchases of one product respond to a price change in a different product.",
      "Coffee gets pricier, so tea sales rise.",
      ["cross-price elasticity", "cross price elasticity"]),
    T("tax incidence", "who really ends up paying a tax",
      "The question of who bears the cost of a tax, which is often not the person who hands the money over.",
      "A tax on landlords ends up in higher rents, so tenants pay part of it.",
      ["incidence of a tax", "incidence of the tax"]),

    # ------------------------------------------------ ch7: welfare economics
    T("welfare economics", "the study of how well off policies leave people",
      "The branch of economics that asks whether an arrangement makes people better or worse off overall.",
      "Working out whether a new bridge is worth its cost to everyone affected."),
    T("willingness to pay", "the most someone would pay",
      "The top price a buyer would hand over for something.",
      "You'd pay up to $40 for the concert, so at $25 you feel like you got a deal.",
      ["willing to pay", "reservation price"]),

    # ------------------------------------------------ ch10-11: externalities, public goods
    T("internalizing the externality", "making people feel the side effects of their actions",
      "Changing incentives so that people take into account the costs or benefits they impose on others.",
      "A carbon tax makes a polluter pay for the harm it causes.",
      ["internalize the externality", "internalise the externality", "internalizing an externality", "internalizing externalities"]),
    T("corrective tax", "a tax that makes polluters pay for the harm they cause",
      "A tax designed to make a business or person face the cost they impose on others.",
      "A tax on cigarettes or carbon emissions.",
      ["corrective taxes", "pigouvian tax", "pigovian tax", "pigouvian taxes"],
      plural="taxes that make polluters pay for the harm they cause"),
    T("coase theorem", "people can fix side effects by bargaining if bargaining is cheap",
      "The idea that if the people involved can negotiate easily, they will sort out an externality themselves without government help.",
      "A neighbor pays the other to keep the dog quiet, or vice versa, whoever values it more.",
      ["the coase theorem"]),
    T("transaction costs", "the hassle and expense of making a deal",
      "The time, money, and effort it takes to reach and enforce an agreement.",
      "Lawyer fees, haggling, and paperwork when selling a house.",
      ["transaction cost"]),
    T("excludability", "being able to stop people who don't pay",
      "Whether a seller can keep non-payers from using something.",
      "A cinema can stop you at the door; a fireworks show cannot.",
      ["excludable", "non-excludable", "nonexcludable"]),
    T("rivalry in consumption", "one person's use leaves less for others",
      "Whether one person using something reduces what is left for everyone else.",
      "A slice of pizza is rival; a radio broadcast is not.",
      ["rival in consumption", "rivalrous", "non-rival", "nonrival"]),
    T("private goods", "things you can be charged for and that get used up",
      "Goods that a seller can withhold from non-payers and that one person's use leaves less for others. Most things in shops.",
      "A sandwich.",
      ["private good"]),
    T("club goods", "things you can be charged for but that don't run out",
      "Goods that non-payers can be excluded from, but that many people can use at once without using them up.",
      "Netflix or a private golf course.",
      ["club good"]),
    T("common resources", "shared things anyone can use but that run out",
      "Goods that nobody can be stopped from using, but that get depleted as people use them.",
      "Fish in the ocean, a public parking lot.",
      ["common resource"]),
    T("free rider", "someone who benefits without paying",
      "A person who enjoys something others paid for while contributing nothing.",
      "Watching the town fireworks without chipping in.",
      ["free riders", "free-rider", "free-riders", "free rider problem", "free-rider problem"],
      plural="people who benefit without paying"),
    T("cost-benefit analysis", "weighing what something costs against what it's worth",
      "Adding up all the costs and all the benefits of a project to see if it is worth doing.",
      "Is a $2 million bridge worth it if it saves each commuter 20 minutes a day?",
      ["cost–benefit analysis", "cost benefit analysis"]),

    # ------------------------------------------------ ch12: taxes
    T("average tax rate", "the share of your total income paid in tax",
      "Total taxes divided by total income.",
      "Earn $50k, pay $8k tax: a 16% average rate."),
    T("lump-sum tax", "a tax that is the same amount for everyone",
      "A fixed tax that does not change with income or spending.",
      "Every adult pays $1,000, whether they earn $20k or $2M.",
      ["lump sum tax", "lump-sum taxes", "poll tax"]),
    T("benefits principle", "you pay for what you use",
      "The idea that taxes should be based on how much a person benefits from government services.",
      "Gas taxes paying for roads: drivers pay, drivers benefit.",
      ["the benefits principle"]),
    T("ability-to-pay principle", "those who can afford more should pay more",
      "The idea that taxes should be based on how easily a person can bear them.",
      "A millionaire paying a higher share than a cashier.",
      ["ability to pay principle", "ability to pay"]),
    T("vertical equity", "richer people paying more",
      "The idea that people with more ability to pay should pay more tax.",
      "A higher tax bracket for higher earners."),
    T("horizontal equity", "similar people paying similar tax",
      "The idea that people in the same financial position should pay the same tax.",
      "Two families earning $60k paying the same, regardless of how they earned it."),
    T("proportional tax", "a flat-rate tax",
      "A tax that takes the same percentage from everyone regardless of income.",
      "Everyone pays 15%, whether they earn $30k or $300k.",
      ["proportional taxes", "flat tax"]),

    # ------------------------------------------------ ch13-14: costs, competition
    T("total revenue", "all the money a business takes in",
      "Price times quantity sold, before any costs are subtracted.",
      "100 lemonades at $2 each: $200.",
      ["total revenues"]),
    T("total cost", "everything a business spends to produce",
      "The full amount a business pays for all its inputs.",
      "Lemons, sugar, cups, and the stand: $60.",
      ["total costs"]),
    T("explicit costs", "costs paid out in cash",
      "Expenses that involve actually handing over money.",
      "Rent, wages, ingredients.",
      ["explicit cost"]),
    T("implicit costs", "costs of what you gave up, with no cash paid",
      "Costs that do not involve a payment, like the salary you could have earned elsewhere.",
      "Quitting a $60k job to open a cafe costs you $60k a year, even though you never write a check.",
      ["implicit cost"]),
    T("accounting profit", "revenue minus cash expenses",
      "What is left after subtracting only the costs actually paid out.",
      "Cafe takes in $150k and pays $100k in bills: $50k accounting profit.",
      ["accounting profits"]),
    T("economic profit", "revenue minus all costs, including what you gave up",
      "Profit after subtracting both the bills paid and the value of the alternatives you sacrificed.",
      "That $50k accounting profit is really a $10k loss if you gave up a $60k job for it.",
      ["economic profits", "economic loss"]),
    T("production function", "how much output you get from a given amount of input",
      "The relationship between the inputs a business uses and how much it produces.",
      "One baker makes 50 loaves, two make 90, three make 120.",
      ["production functions"]),
    T("marginal product", "the extra output from one more unit of input",
      "How much more gets produced when one more worker or machine is added.",
      "Adding a second baker raises output from 50 to 90 loaves, so their marginal product is 40.",
      ["marginal products"]),
    T("marginal product of labor", "the extra output from one more worker",
      "How much more a business produces when it hires one additional worker.",
      "The third baker adds 30 loaves a day.",
      ["marginal product of labour"]),
    T("diminishing marginal product", "each extra worker adds less than the last",
      "The pattern where adding more of one input, with everything else fixed, yields smaller and smaller gains.",
      "The tenth cook in a tiny kitchen mostly gets in the way."),
    T("fixed costs", "costs you pay no matter how much you make",
      "Expenses that stay the same regardless of output.",
      "Rent on the shop is due whether you sell 10 pies or 1,000.",
      ["fixed cost", "total fixed cost"]),
    T("average total cost", "the cost per unit",
      "Total cost divided by the number of units made.",
      "$1,000 of costs for 500 pies: $2 per pie.",
      ["average cost", "atc", "unit cost"]),
    T("average fixed cost", "the fixed cost spread per unit",
      "Fixed costs divided by the number of units made. It falls as you make more.",
      "$500 rent over 500 pies is $1 each; over 1,000 pies it is 50 cents.",
      ["afc"]),
    T("average variable cost", "the variable cost per unit",
      "Variable costs divided by the number of units made.",
      "$500 of ingredients for 500 pies: $1 per pie.",
      ["avc"]),
    T("average revenue", "the money taken in per unit",
      "Total revenue divided by the number of units sold. For most sellers it equals the price.",
      "$1,000 from 500 pies: $2 each."),
    T("efficient scale", "the output level with the lowest cost per unit",
      "The amount of production at which the cost per unit is as low as it gets.",
      "The bakery is cheapest per loaf when it bakes about 800 a day.",
      ["minimum efficient scale"]),
    T("constant returns to scale", "cost per unit stays the same as you grow",
      "When doubling all inputs doubles output, so the cost per unit does not change.",
      "Two identical food trucks cost twice as much and make twice the tacos."),
    T("diseconomies of scale", "getting more expensive per unit as you grow",
      "When a business gets so large that each extra unit costs more, usually because it becomes hard to manage.",
      "A chain so big that head office cannot keep track of its stores."),

    # ------------------------------------------------ ch15-17: monopoly, oligopoly, competition
    T("natural monopoly", "a market where one big supplier is cheapest",
      "A situation where one company can serve the whole market more cheaply than two or more could, usually because of huge setup costs.",
      "Water pipes: it makes no sense to lay two sets of pipes down every street.",
      ["natural monopolies"]),
    T("price discrimination", "charging different people different prices for the same thing",
      "Selling the same product at different prices to different customers based on what they are willing to pay.",
      "Student discounts, senior fares, and cheaper matinee tickets.",
      ["price discriminate", "price discriminating"]),
    T("monopolistic competition", "many sellers with slightly different products",
      "A market with many competitors whose products are similar but not identical, so each has a little pricing power.",
      "Restaurants, hair salons, coffee shops."),
    T("nash equilibrium", "a standoff where no one gains by changing alone",
      "A situation where each person is doing the best they can given what everyone else is doing, so nobody wants to change.",
      "Two gas stations across the street both charging $3.50: neither gains by moving first.",
      ["nash equilibria"]),
    T("dominant strategy", "the best move no matter what others do",
      "A choice that works out best for you regardless of what the other players choose.",
      "Confessing in the prisoners' dilemma is best whether or not your partner confesses.",
      ["dominant strategies"]),

    # ------------------------------------------------ ch18-20: labor markets
    T("value of the marginal product", "what one more worker's output is worth",
      "The extra output from one more worker, multiplied by the price it sells for. It tells a business the most it should pay that worker.",
      "A barista who brings in $25 an hour of extra coffee sales is worth up to $25 an hour.",
      ["value of marginal product", "vmp"]),
    T("compensating differential", "extra pay for an unpleasant or risky job",
      "A wage difference that makes up for a job being dirtier, more dangerous, or less pleasant.",
      "Night-shift workers and offshore oil riggers earning more for the same skill level.",
      ["compensating differentials", "compensating wage differential"]),
    T("efficiency wages", "paying above the going rate to get better work",
      "Wages deliberately set higher than necessary so workers try harder and stay longer.",
      "Henry Ford doubling wages to $5 a day to cut turnover.",
      ["efficiency wage"]),
    T("signaling", "doing something visible to prove your quality",
      "Taking an action, like getting a degree, mainly to show others something they cannot see directly.",
      "A college diploma telling employers you can finish hard things.",
      ["signalling"]),
    T("screening", "testing people to sort out the good ones",
      "Actions an uninformed party takes to learn what the other side knows.",
      "An insurer requiring a medical exam before selling life insurance."),
    T("discrimination", "discrimination",
      "In economics, paying or treating people differently based on race, sex, age, or similar traits rather than their productivity.",
      "Two equally skilled applicants, one offered less because of their gender.",
      keep=True),
    T("statistical discrimination", "judging a person by their group's average",
      "Treating an individual based on averages about their group, rather than facts about them.",
      "Charging young drivers more for insurance because young drivers crash more on average."),
    T("union", "union",
      "A group of workers who bargain together with their employer over pay and conditions.",
      "Teachers negotiating a contract as one block instead of one by one.",
      ["labor union", "labour union", "trade union", "unions"],
      keep=True),
    T("strike", "strike",
      "Workers refusing to work, as a group, to pressure the employer into a better deal.",
      "Auto workers walking out until they get a raise.",
      ["strikes"],
      keep=True),
    T("in-kind transfers", "help given as goods or services instead of cash",
      "Government aid that comes as actual stuff, not money.",
      "Food stamps, housing vouchers, free school lunches.",
      ["in-kind transfer", "in kind transfers"]),
    T("negative income tax", "the government paying money to low earners",
      "A system where people below a certain income receive a payment instead of paying tax.",
      "Earn $10k and get a $3k check from the government."),
    T("social insurance", "government programs that protect against bad luck",
      "Programs everyone pays into that pay out when someone is hit by unemployment, illness, or old age.",
      "Unemployment benefits and Social Security."),
    T("permanent income", "your normal long-run income",
      "What a person expects to earn on average over their life, ignoring temporary ups and downs.",
      "A commission salesperson who spends based on their typical year, not a bumper month."),
    T("life cycle", "the pattern of earning and spending over a lifetime",
      "The regular pattern of low income when young, high income mid-career, and low income in retirement.",
      "Borrowing as a student, saving in your forties, spending savings at seventy.",
      ["life-cycle", "lifecycle"]),
    T("utilitarianism", "aim for the greatest total happiness",
      "The view that policy should maximize the total well-being of everyone in society added together.",
      "Taking $1 from a millionaire to give a hungry person a meal, because it raises total happiness."),
    T("liberal contractarianism", "design society as if you didn't know who you'd be",
      "The view, from philosopher John Rawls, that fair rules are the ones you would choose without knowing whether you would end up rich or poor.",
      "Picking the rules of a game before you know which team you will play for.",
      ["rawlsian"]),
    T("maximin criterion", "make the worst-off person as well off as possible",
      "The idea that a society should judge itself by how its poorest member is doing.",
      "Judging a school by how its weakest student does, not its star pupil.",
      ["maximin"]),
    T("libertarianism", "let people keep what they earn",
      "The view that the government should protect property rights and enforce contracts but not redistribute income.",
      "Arguing that taxing one person to help another is unjust however good the cause.",
      ["libertarian"]),

    # ------------------------------------------------ ch21: consumer choice
    T("budget constraint", "what you can afford",
      "The limit on the combinations of things a person can buy with their income.",
      "With $20 you can get four coffees, or two coffees and a sandwich, but not both maxed.",
      ["budget constraints", "budget line"]),
    T("indifference curve", "the line of combinations you like equally",
      "A curve showing all the mixes of two things that give a person the same satisfaction.",
      "Three pizzas and one movie feels just as good to you as one pizza and three movies.",
      ["indifference curves"],
      plural="lines of combinations you like equally"),
    T("marginal rate of substitution", "how much of one thing you'd trade for one more of another",
      "The rate at which a person is willing to swap one good for another while staying equally happy.",
      "Giving up two sodas for one extra slice of pizza.",
      ["mrs"]),
    T("income effect", "buying more because you feel richer",
      "The change in what you buy that happens because a price change leaves you with more or less spending power.",
      "Gas gets cheaper, so you feel richer and eat out more.",
      ["income effects"]),
    T("substitution effect", "switching to what got relatively cheaper",
      "The change in what you buy that happens because one thing is now a better deal compared to another.",
      "Beef gets pricier, so you buy chicken instead.",
      ["substitution effects"]),
    T("giffen good", "a rare thing people buy more of when its price rises",
      "An unusual product where a price increase actually raises the amount bought, because poor buyers can no longer afford anything else.",
      "Rice for a very poor family: pricier rice leaves no money for meat, so they eat even more rice.",
      ["giffen goods"]),
    T("risk aversion", "disliking uncertainty",
      "Preferring a sure thing over a gamble with the same average payoff.",
      "Taking $50 for certain rather than a coin flip for $100 or nothing.",
      ["risk averse", "risk-averse"]),
    T("principal-agent problem", "someone acting for you not fully sharing your goals",
      "The tension when one person (the agent) makes decisions on behalf of another (the principal) but has different interests.",
      "A real estate agent nudging you to accept a quick sale because their commission is nearly the same either way.",
      ["principal–agent problem", "agency problem", "principal-agent", "principal and agent"]),

    # ------------------------------------------------ ch22: political economy
    T("political economy", "how politics shapes economic decisions",
      "The study of how governments actually make economic choices, given voters, politicians, and their incentives.",
      "Why a subsidy survives long after economists say it should go."),
    T("condorcet paradox", "majority votes can go round in circles",
      "The finding that majority voting can rank A over B, B over C, and yet C over A, so there is no clear winner.",
      "Three friends voting on pizza, tacos, or sushi and never settling it.",
      ["condorcet's paradox"]),
    T("arrow's impossibility theorem", "no voting system is perfectly fair",
      "A proof that no method of combining people's rankings into a group ranking can satisfy every reasonable fairness rule at once.",
      "Every election system has some situation where it gives an odd result.",
      ["arrow's theorem", "impossibility theorem"]),
    T("median voter theorem", "politicians chase the voter in the middle",
      "The idea that in a majority vote, the outcome ends up being what the middle-of-the-road voter wants.",
      "Both parties drifting toward the center before an election.",
      ["median voter"]),

    # ------------------------------------------------ appendix: data & econometrics
    T("econometrics", "using statistics on economic data",
      "The toolkit economists use to test theories with real-world numbers.",
      "Estimating how much a 10% price cut boosts sales by crunching past sales data.",
      ["econometric"]),
    T("randomized controlled trial", "an experiment with a coin-flip control group",
      "A study where people are randomly assigned to get a treatment or not, so the two groups can be fairly compared.",
      "Randomly giving half the villages cash grants and comparing them to the other half.",
      ["randomized controlled trials", "rct", "rcts", "randomised controlled trial"]),
    T("experimental data", "numbers from a controlled experiment",
      "Data collected by deliberately changing one thing and watching what happens.",
      "Sales figures from stores where you randomly changed the price."),
    T("observational data", "numbers from watching the real world",
      "Data collected by observing what happens naturally, without controlling anything.",
      "Past sales figures and past prices, just as they happened."),
    T("natural experiment", "a real-world event that acts like an experiment",
      "A situation where something outside anyone's control splits people into groups that can be compared.",
      "Comparing two neighboring states after one raises its minimum wage.",
      ["natural experiments"]),
    T("confounding variable", "a hidden factor that muddles the result",
      "Something left out of the analysis that affects both the cause and the effect you are studying, making them look linked.",
      "Ice cream sales and drowning both rise in summer; hot weather is the hidden factor.",
      ["confounding variables", "confounder", "confounders", "omitted variable"]),
    T("reverse causality", "the effect actually causing the cause",
      "Mistaking which way the influence runs between two things.",
      "Do police cause crime because high-crime cities have more police? No, crime causes more police.",
      ["reverse causation"]),
    T("cross-sectional data", "a snapshot of many people at one time",
      "Data on many different people, firms, or places measured at a single point in time.",
      "The incomes of 1,000 households this year.",
      ["cross-section data", "cross sectional data"]),
    T("time-series data", "one thing tracked over time",
      "Data on a single person, firm, or place measured repeatedly over many periods.",
      "US unemployment every month since 1950.",
      ["time series data", "time series"]),
    T("panel data", "many people tracked over time",
      "Data that follows the same group of people, firms, or places across several periods.",
      "The same 1,000 households surveyed every year for a decade.",
      ["longitudinal data"]),
    T("linear regression", "fitting a straight line through the data",
      "A statistical method that finds the straight line best describing how one thing changes with another.",
      "Drawing the best line through a scatter of price and sales points to see how much sales drop per dollar.",
      ["regression", "regressions", "regression analysis"]),
    T("multiple regression", "fitting a line with several factors at once",
      "A regression that accounts for more than one influence at the same time.",
      "Estimating how price, advertising, and weather together affect sales."),
    T("ordinary least squares", "the standard way to fit the line",
      "The usual method for fitting a regression: choose the line that keeps the total squared gaps to the data smallest.",
      "The line that comes closest to all the dots at once.",
      ["ols"]),
    T("standard error", "how uncertain an estimate is",
      "A measure of how much an estimated number would bounce around if you repeated the study with new data.",
      "An effect of 5 with a standard error of 1 is solid; with a standard error of 6 it could easily be zero.",
      ["standard errors"]),
]

# Wordy phrasing common in the textbook and slides.
TEXTBOOK_SIMPLIFICATIONS = {
    "allocate": "divide up",
    "allocates": "divides up",
    "allocated": "divided up",
    "allocating": "dividing up",
    "allocation of resources": "how resources get divided up",
    "resource allocation": "how resources get divided up",
    "allocation": "division",
    "phenomena": "things that happen",
    "phenomenon": "thing that happens",
    "fluctuations": "ups and downs",
    "fluctuation": "up-and-down swing",
    "fluctuate": "go up and down",
    "feasible": "possible",
    "infeasible": "impossible",
    "prescriptive": "opinion-based",
    "descriptive": "fact-based",
    "induces": "pushes",
    "induce": "push",
    "unduly": "unfairly",
    "incremental": "step-by-step",
    "systematically": "consistently",
    "purposefully": "on purpose",
    "refute": "disprove",
    "refuted": "disproved",
    "verify": "confirm",
    "devise": "come up with",
    "policymakers": "the people who set government policy",
    "policy makers": "the people who set government policy",
    "bystander": "someone not involved",
    "bystanders": "people not involved",
    "prosperity": "wealth",
    "uniformly": "evenly",
    "obtain": "get",
    "attain": "reach",
    "quantity": "amount",
    "quantities": "amounts",
    "excessive": "too much",
    "stimulates": "boosts",
    "stimulate": "boost",
    "interact": "deal with one another",
    "interaction": "dealings",
    "unintended consequences": "side effects nobody planned",
    "well-being": "quality of life",
    "specialize": "focus on what they do best",
    "specialise": "focus on what they do best",
    "specialization": "each focusing on what they do best",
    "specialisation": "each focusing on what they do best",
    "society's resources": "everything a country has to work with",
    "scarce resources": "limited resources",
    "inputs": "ingredients and tools",
    "outputs": "what gets made",
    "the long run": "the long term",
    "the short run": "the short term",
    "long-run": "long-term",
    "short-run": "short-term",
    "economic activity": "buying, selling, and working",
    "economic outcomes": "how things turn out for people's money",
    "economic prosperity": "wealth",
    "goods and services": "products",
    "hypothesis": "an idea to test",
    "empirically": "using real data",
    "in aggregate": "added up",
    "aggregate": "total",
    "optimize": "get the best result",
    "optimizing": "getting the best result",
    "maximize": "get the most",
    "maximizes": "gets the most",
    "minimize": "keep as low as possible",
    "minimizes": "keeps as low as possible",
}
