"""
Economics glossary for the Layman's Translator.

Each entry maps a term to:
  plain    - a short phrase that can replace the term inside a sentence
  meaning  - one or two plain sentences explaining it
  example  - an everyday example
  aliases  - other spellings/forms of the term (used for matching in both
             directions; the reverse direction also matches `plain`)

Keep `plain` short and grammatical as a drop-in replacement. Keep `meaning`
free of other jargon wherever possible.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Term:
    term: str
    plain: str
    meaning: str
    example: str
    aliases: tuple = field(default_factory=tuple)
    plural: str = ""    # plain phrase to use when the term appears in plural
    keep: bool = False  # True: leave the word in the sentence, only explain it


def T(term, plain, meaning, example, aliases=(), plural="", keep=False):
    return Term(term, plain, meaning, example, tuple(aliases), plural, keep)


TERMS = [
    # ---------------------------------------------------------------- prices
    T("inflation", "rising prices",
      "Prices of most things going up over time, so each dollar buys a little less than it used to.",
      "A coffee that cost $3 last year costs $3.20 this year.",
      ["inflationary", "price inflation"]),
    T("deflation", "falling prices",
      "Prices of most things going down over time. Sounds nice, but people delay buying and businesses earn less.",
      "A TV that cost $500 last year costs $450 now, so you wait to see if it drops more.",
      ["deflationary"]),
    T("disinflation", "prices rising more slowly",
      "Prices are still going up, just not as fast as before.",
      "Prices rose 8% last year but only 3% this year."),
    T("stagflation", "stalled growth with rising prices",
      "The worst of both worlds: prices keep going up while jobs and growth are stuck.",
      "Groceries get pricier every month while your employer freezes hiring."),
    T("hyperinflation", "runaway rising prices",
      "Prices rising so fast that money loses value week to week or even day to day.",
      "A loaf of bread costs twice as much on Friday as it did on Monday."),
    T("consumer price index", "the everyday-prices index",
      "A monthly measure of what a typical basket of household goods and services costs. It is the usual way inflation is tracked.",
      "If the index rises 3%, the same groceries, rent, and gas cost about 3% more than a year ago.",
      ["cpi", "core cpi", "headline cpi"]),
    T("core inflation", "rising prices excluding food and energy",
      "Inflation measured without food and fuel, because those prices swing around a lot and can hide the underlying trend.",
      "Gas spiked this month, but core inflation shows most other prices barely moved."),
    T("cost of living", "what everyday life costs",
      "How much money it takes to cover basics like housing, food, and transport in a given place.",
      "The same salary stretches further in a small town than in a big city."),
    T("purchasing power", "how much your money actually buys",
      "The real value of money measured by what it can buy, not the number printed on it.",
      "$100 bought a full cart of groceries in 2010 and about half a cart now."),
    T("real terms", "after adjusting for rising prices",
      "A number that has been corrected for inflation so you can compare different years fairly.",
      "A 5% raise when prices rose 6% is a pay cut in real terms.",
      ["in real terms", "inflation-adjusted", "inflation adjusted"]),
    T("nominal", "before adjusting for rising prices",
      "The raw dollar number, not corrected for inflation.",
      "Your nominal pay went from $50k to $52k, but if prices rose 5%, you can actually buy less.",
      ["in nominal terms", "nominal terms"]),
    T("price level", "the general level of prices",
      "The average of all prices in the economy at a point in time.",
      "When the price level rises, nearly everything, from rent to haircuts, costs more."),
    T("price ceiling", "a legal maximum price",
      "A cap set by the government on how much something can be sold for.",
      "Rent control that stops a landlord from charging more than $1,500 a month."),
    T("price floor", "a legal minimum price",
      "A bottom limit set by the government on how cheaply something can be sold.",
      "The minimum wage is a price floor on what an hour of work can be paid."),
    T("sticky prices", "prices that are slow to change",
      "Prices and wages that do not adjust quickly even when conditions change.",
      "A restaurant keeps its menu prices the same for a year because reprinting menus is a hassle.",
      ["price stickiness", "sticky wages"]),

    # ------------------------------------------------------- output & growth
    T("gross domestic product", "the total value of everything a country produces",
      "The total value of all goods and services made in a country in a year. It is the standard scorecard for the size of an economy.",
      "Every car built, haircut given, and app sold in the US in a year, added up into one number.",
      ["gdp", "real gdp", "nominal gdp"]),
    T("gdp per capita", "output per person",
      "The country's total output divided by its population. A rough guide to average living standards.",
      "Two countries can have the same GDP, but the one with fewer people is richer per person.",
      ["per capita gdp", "per capita income", "per capita"]),
    T("economic growth", "the economy getting bigger",
      "The economy producing more stuff than it did before, usually measured as a percentage change per year.",
      "The economy grew 2%, meaning the country made about 2% more goods and services than last year.",
      ["growth rate", "gdp growth"]),
    T("recession", "a shrinking economy",
      "A period, usually a few months or more, when the economy shrinks: less is produced, businesses cut back, and people lose jobs.",
      "Stores close, hiring stops, and your neighbors get laid off.",
      ["recessionary", "economic downturn", "downturn", "contraction"],
      plural="shrinking economies"),
    T("depression", "a deep, long-lasting shrinking economy",
      "A very severe recession that lasts years rather than months.",
      "The 1930s, when a quarter of workers had no job.",
      ["economic depression", "great depression"]),
    T("recovery", "bounce-back",
      "The period after a recession when output and jobs start growing again.",
      "Restaurants reopen and start hiring again after a bad year.",
      ["economic recovery"]),
    T("expansion", "growth period",
      "A stretch of time when the economy is getting bigger.",
      "Years when businesses keep opening and unemployment keeps falling.",
      ["economic expansion"]),
    T("business cycle", "the economy's ups and downs",
      "The natural pattern of the economy growing, then shrinking, then growing again over several years.",
      "Boom years followed by a slump followed by another boom.",
      ["economic cycle"]),
    T("soft landing", "slowing the economy without a crash",
      "When a central bank cools down an overheated economy just enough to tame inflation without causing a recession.",
      "Braking gently to slow a car rather than slamming the brakes."),
    T("hard landing", "slowing the economy so much it crashes",
      "When efforts to cool inflation push the economy into a recession.",
      "Hitting the brakes so hard the car skids."),
    T("productivity", "output per hour of work",
      "How much gets made for each hour worked. Higher productivity means more stuff from the same effort.",
      "A worker with a power drill builds more furniture per day than one with a screwdriver.",
      ["labor productivity", "labour productivity"]),
    T("output", "production",
      "The total goods and services made.",
      "A factory's output is the number of cars it builds."),
    T("output gap", "the gap between what the economy makes and what it could make",
      "The difference between actual production and what the economy could produce if everyone and everything were fully used.",
      "A factory running at 70% capacity has a 30% gap."),
    T("potential output", "what the economy could make at full stretch",
      "The most the economy could produce without pushing prices up too fast.",
      "The top speed a car can safely go for a long trip.",
      ["potential gdp"]),
    T("aggregate demand", "total spending in the economy",
      "All the spending by households, businesses, government, and foreigners on a country's goods and services, added together.",
      "Everyone's shopping, every company's investment, and government projects, all combined."),
    T("aggregate supply", "total production in the economy",
      "Everything businesses in a country are willing and able to make at a given price level.",
      "All the factories, farms, and shops together deciding how much to produce."),
    T("consumption", "household spending",
      "Money that people spend on goods and services for themselves.",
      "Groceries, rent, Netflix, and new shoes.",
      ["consumer spending", "personal consumption"]),
    T("investment", "spending on buildings and machines",
      "In economics, money spent on buildings, machines, and tools that help make more things later. Not the same as buying stocks.",
      "A bakery buying a new oven.",
      ["capital investment", "business investment", "gross fixed capital formation"]),
    T("capital", "tools, buildings, and machines",
      "The physical stuff, and sometimes the money, a business uses to produce goods and services.",
      "A carpenter's workshop and tools.",
      ["capital goods", "physical capital", "capital stock"]),
    T("human capital", "people's skills and knowledge",
      "The education, training, and experience that make workers more valuable.",
      "A nurse's years of training."),
    T("labor", "workers",
      "The people and the work they do to produce things.",
      "Every employee from cashier to CEO.",
      ["labour", "labor force", "labour force", "workforce"]),
    T("factors of production", "the basic ingredients for making things",
      "Land, workers, tools, and know-how: the inputs every business needs.",
      "For a farm: the field, the farmers, the tractor, and the owner's judgment."),

    # ------------------------------------------------------------------ jobs
    T("unemployment", "the number of people who can't find work",
      "The share of people who are looking for work but do not have a job.",
      "Out of 100 people who want a job, 5 cannot find one, so unemployment is 5%.",
      ["unemployment rate", "joblessness", "jobless rate"]),
    T("full employment", "nearly everyone who wants a job has one",
      "The point where unemployment is as low as it can realistically go, with only people between jobs still looking.",
      "Every restaurant in town has a 'now hiring' sign."),
    T("underemployment", "having less work than you want",
      "Working part time when you want full time, or in a job below your skill level.",
      "An engineer driving a taxi while looking for engineering work.",
      ["underemployed"]),
    T("structural unemployment", "joblessness because skills no longer match the jobs",
      "People out of work because the jobs they know how to do have disappeared or moved.",
      "Coal miners in a town where the mine closed."),
    T("cyclical unemployment", "joblessness caused by a weak economy",
      "People losing jobs because the economy is in a slump, not because of their skills.",
      "A construction worker laid off during a housing bust."),
    T("frictional unemployment", "joblessness from being between jobs",
      "Short spells of unemployment as people move between jobs or enter the workforce.",
      "A new graduate spending two months job hunting."),
    T("labor force participation rate", "the share of adults working or looking for work",
      "The percentage of working-age people who either have a job or are actively looking for one.",
      "Retirees and stay-at-home parents are not counted as participating.",
      ["labour force participation rate", "participation rate"]),
    T("nonfarm payrolls", "the monthly jobs count",
      "The US government's monthly count of how many jobs were added or lost, excluding farm work.",
      "Headlines like 'the economy added 200,000 jobs last month'.",
      ["non-farm payrolls", "payrolls", "jobs report"]),
    T("minimum wage", "the lowest legal pay",
      "The least an employer is legally allowed to pay per hour.",
      "A cashier must be paid at least $15 an hour in some states."),
    T("wage growth", "pay rising",
      "How fast workers' pay is going up over time.",
      "Average hourly pay rose 4% over the year."),
    T("real wages", "pay after adjusting for rising prices",
      "What your paycheck can actually buy, once inflation is accounted for.",
      "A 3% raise when prices rose 3% means your real wage did not change.",
      ["real wage", "real income"]),
    T("disposable income", "take-home pay",
      "The money you have left after taxes to spend or save.",
      "Your paycheck after taxes come out."),
    T("discretionary income", "spending money",
      "What is left after taxes and essentials like rent and food.",
      "The money you can spend on a concert or a vacation."),

    # ------------------------------------------------------- money & banking
    T("monetary policy", "the central bank's control of interest rates and money",
      "The tools a central bank uses, mainly interest rates, to keep prices stable and the economy steady.",
      "The Fed raising rates to cool inflation."),
    T("fiscal policy", "the government's taxing and spending",
      "How the government uses taxes and spending to influence the economy.",
      "Sending stimulus checks or cutting taxes during a slump."),
    T("central bank", "the country's main bank",
      "The institution that controls a country's money supply and interest rates.",
      "The Federal Reserve in the US or the Bank of England in the UK.",
      ["federal reserve", "the fed", "ecb", "european central bank", "bank of england", "boe", "bank of japan", "boj"]),
    T("federal reserve", "the Fed",
      "America's central bank. It sets the key interest rate, and its decisions ripple out to mortgages, car loans, and credit cards.",
      "When the news says 'the Fed raised rates', your credit card interest will probably go up too.",
      ["the fed", "fed", "the federal reserve", "fomc"],
      keep=True),
    T("interest rate", "the cost of borrowing money",
      "The percentage you pay to borrow money, or earn for lending it.",
      "Borrow $1,000 at 5% and you owe $50 extra a year.",
      ["interest rates", "policy rate"],
      plural="borrowing costs"),
    T("federal funds rate", "the Fed's key interest rate",
      "The rate banks charge each other for overnight loans, set by the Federal Reserve. Most other interest rates follow it.",
      "When this goes up, mortgage and credit card rates soon go up too.",
      ["fed funds rate", "funds rate", "benchmark rate", "base rate", "bank rate"]),
    T("rate hike", "an interest rate increase",
      "The central bank raising its main interest rate to make borrowing more expensive.",
      "After a rate hike, a new car loan costs more per month.",
      ["rate hikes", "hiking rates", "monetary tightening"],
      plural="interest rate increases"),
    T("rate cut", "an interest rate decrease",
      "The central bank lowering its main interest rate to make borrowing cheaper.",
      "After a rate cut, mortgages get cheaper and more people buy homes.",
      ["rate cuts", "cutting rates", "monetary easing"],
      plural="interest rate cuts"),
    T("quantitative easing", "the central bank creating money to buy bonds",
      "A central bank buying large amounts of bonds with newly created money to push interest rates down and encourage lending.",
      "Like the Fed flooding the system with cash to keep borrowing cheap.",
      ["qe"]),
    T("quantitative tightening", "the central bank shrinking the money it created",
      "The reverse of quantitative easing: the central bank lets its bond holdings shrink, pulling money out of the system.",
      "The Fed slowly draining the extra cash it pumped in earlier.",
      ["qt"]),
    T("money supply", "the total amount of money in the economy",
      "All the cash and bank deposits available in the economy.",
      "Every dollar in wallets and checking accounts added together.",
      ["m1", "m2", "money stock"]),
    T("liquidity", "how easily something turns into cash",
      "How quickly and cheaply you can convert something into spendable money. Also used for how much ready cash is sloshing around.",
      "Cash is very liquid; a house is not, because selling it takes months.",
      ["liquid"]),
    T("illiquid", "hard to turn into cash",
      "Something that cannot be sold quickly without losing value.",
      "A rare painting or a house.",
      ["illiquidity"]),
    T("reserve requirement", "the cash banks must keep on hand",
      "The minimum share of deposits a bank must hold rather than lend out.",
      "If you deposit $100 and the requirement is 10%, the bank keeps $10 and can lend $90.",
      ["reserve ratio", "bank reserves"]),
    T("fractional reserve banking", "banks lending out most of what you deposit",
      "The system where banks keep only a fraction of deposits in reserve and lend the rest.",
      "Your $1,000 deposit becomes someone else's $900 car loan."),
    T("bank run", "everyone rushing to pull their money out of a bank",
      "When many customers withdraw at once because they fear the bank will fail, which can actually cause it to fail.",
      "Lines around the block at a bank in 1930, or a viral tweet emptying accounts overnight."),
    T("lender of last resort", "the emergency lender to banks",
      "A central bank's role of lending to banks that cannot borrow anywhere else, to stop a panic.",
      "The Fed lending to a bank so it can pay depositors during a scare."),
    T("credit", "borrowed money",
      "Money lent to a person or business that must be paid back, usually with interest.",
      "A credit card, a mortgage, or a business loan.",
      ["credit conditions"]),
    T("credit crunch", "a sudden shortage of loans",
      "When banks abruptly stop lending or make loans much harder to get.",
      "Businesses with good records suddenly cannot get a loan to make payroll.",
      ["credit squeeze"]),
    T("leverage", "borrowed money",
      "Using debt to make a bigger bet or purchase than you could with your own money alone. It magnifies both gains and losses.",
      "Buying a $500k house with $50k down: a 10% price rise doubles your money, a 10% fall wipes it out.",
      ["leveraging"]),
    T("leveraged", "debt-funded",
      "Done with a lot of borrowed money, which magnifies both gains and losses.",
      "A leveraged buyout is a company purchase paid for mostly with loans."),
    T("deleveraging", "paying down debt",
      "Reducing how much borrowed money is being used.",
      "A family cutting spending to pay off credit cards.",
      ["deleverage"]),
    T("solvency", "being able to pay all your debts",
      "Having more assets than debts, so you could pay everything you owe if you had to.",
      "A business that owns $1M of stuff and owes $600k is solvent.",
      ["solvent"]),
    T("insolvency", "owing more than you have",
      "When debts exceed assets and bills cannot be paid.",
      "A company that owes $1M but only has $600k in total.",
      ["insolvent"]),
    T("default", "failing to pay back a loan",
      "Not making the required payments on a debt.",
      "Missing your mortgage payments for months.",
      ["defaulting", "defaulted"]),
    T("moral hazard", "taking risks because someone else will cover the losses",
      "When people behave more recklessly because they know they will be protected from the consequences.",
      "Driving less carefully because you have full insurance."),
    T("bailout", "a rescue with public money",
      "The government stepping in with money to save a failing company or bank.",
      "Taxpayers propping up a bank so it does not collapse.",
      ["bail out", "bailouts"]),

    # ------------------------------------------------------------- government
    T("budget deficit", "the government spending more than it collects",
      "When the government spends more in a year than it takes in through taxes, and borrows to cover the difference.",
      "Earning $50k but spending $55k, and putting the extra on a credit card.",
      ["deficit", "fiscal deficit", "deficit spending"],
      plural="years of the government spending more than it collects"),
    T("budget surplus", "the government collecting more than it spends",
      "When the government takes in more tax than it spends in a year.",
      "Earning $50k and spending only $45k.",
      ["surplus", "fiscal surplus"]),
    T("national debt", "everything the government owes",
      "The total amount the government has borrowed over the years and not yet paid back.",
      "The country's running credit card balance.",
      ["public debt", "government debt", "sovereign debt"]),
    T("debt-to-gdp ratio", "government debt compared to the size of the economy",
      "How big the national debt is relative to what the country produces in a year. A way to judge whether debt is manageable.",
      "Owing $100k on a $100k salary versus a $30k salary.",
      ["debt to gdp", "debt to gdp ratio"]),
    T("austerity", "government spending cuts and tax hikes",
      "Policies that cut public spending or raise taxes to reduce government borrowing.",
      "Closing libraries and raising sales tax to balance the budget.",
      ["austerity measures", "fiscal consolidation"]),
    T("stimulus", "government spending to boost the economy",
      "Extra government spending or tax cuts meant to get a weak economy moving.",
      "Stimulus checks mailed to households during a downturn.",
      ["fiscal stimulus", "economic stimulus", "stimulus package"]),
    T("subsidy", "government money that lowers a price",
      "A payment from the government to make something cheaper to produce or buy.",
      "Tax credits that knock $7,500 off an electric car.",
      ["subsidies", "subsidized", "subsidised"],
      plural="government payments that lower prices"),
    T("tariff", "a tax on imports",
      "A tax charged on goods brought in from another country, which makes them more expensive.",
      "A 25% tariff on foreign steel makes imported steel cost 25% more.",
      ["tariffs", "import duty", "import duties", "customs duty"],
      plural="taxes on imports"),
    T("progressive tax", "a tax that takes a bigger share from higher earners",
      "A tax where the rate goes up as income goes up.",
      "Someone earning $500k pays a higher percentage than someone earning $40k."),
    T("regressive tax", "a tax that hits lower earners harder",
      "A tax that takes a bigger share of income from people who earn less.",
      "Sales tax: a $10 tax is a bigger chunk of a $300 weekly paycheck than a $3,000 one."),
    T("marginal tax rate", "the tax on your next dollar",
      "The rate you pay on the last, or next, dollar you earn, not on all your income.",
      "Being in the 24% bracket does not mean 24% of everything; only income above a threshold is taxed at 24%.",
      ["tax bracket"]),
    T("transfer payments", "government money given to people",
      "Payments from the government to individuals without anything in return, like benefits.",
      "Social Security, unemployment benefits, food stamps.",
      ["social transfers"]),
    T("entitlements", "government benefit programs people qualify for by law",
      "Programs that pay benefits to anyone who meets the rules.",
      "Social Security and Medicare.",
      ["entitlement programs", "entitlement spending"]),
    T("automatic stabilizers", "built-in cushions in the budget",
      "Parts of the tax and benefit system that automatically soften a downturn without new laws.",
      "When people lose jobs, unemployment benefits kick in and their tax bills fall.",
      ["automatic stabilisers"]),
    T("crowding out", "government borrowing squeezing out private borrowing",
      "When heavy government borrowing pushes up interest rates and makes it harder for businesses to borrow.",
      "A big government bond sale soaks up money that would have funded a startup."),
    T("public goods", "things everyone can use and no one can be excluded from",
      "Goods like streetlights or national defense that benefit everyone and cannot easily be sold person by person.",
      "A lighthouse helps every ship, whether or not they paid for it.",
      ["public good"]),
    T("externality", "a side effect on people not involved",
      "A cost or benefit that lands on someone who was not part of the deal.",
      "A factory's pollution making a neighbor sick, or a neighbor's garden making your street nicer.",
      ["externalities", "negative externality", "positive externality", "spillover"],
      plural="side effects on people not involved"),
    T("market failure", "the market getting it wrong on its own",
      "A situation where buying and selling freely leads to a bad outcome for society, so rules may be needed.",
      "Nobody pays for clean air, so factories pollute too much."),
    T("regulation", "government rules for businesses",
      "Laws that limit or direct what businesses can do.",
      "Food safety inspections and limits on bank risk-taking.",
      ["regulatory", "regulations"]),
    T("deregulation", "removing government rules",
      "Loosening or scrapping rules on businesses.",
      "Letting airlines set their own fares and routes."),
    T("nationalization", "the government taking over a business",
      "The government taking ownership of a company or industry.",
      "The state taking over a failing railroad.",
      ["nationalisation", "nationalize", "nationalise"]),
    T("privatization", "selling a government business to private owners",
      "Transferring a state-owned company or service into private hands.",
      "A city selling its water utility to a company.",
      ["privatisation", "privatize", "privatise"]),

    # ---------------------------------------------------------------- markets
    T("supply and demand", "how much is available versus how much people want",
      "The two forces that set prices: how much sellers offer and how much buyers want. Scarce and popular things cost more.",
      "Concert tickets cost more when there are few seats and many fans."),
    T("supply", "how much is available to sell",
      "The amount of something that sellers are willing to offer at a given price.",
      "Farmers bring more tomatoes to market when tomato prices are high.",
      keep=True),
    T("demand", "how much people want to buy",
      "The amount of something that buyers want and can pay for at a given price.",
      "More people want ice cream on a hot day.",
      keep=True),
    T("equilibrium", "the balance point where supply matches demand",
      "The price where the amount people want to buy equals the amount sellers want to sell.",
      "The ticket price where the venue sells out exactly, with no empty seats and no one turned away.",
      ["market equilibrium", "equilibrium price"]),
    T("shortage", "not enough to go around",
      "When people want to buy more of something than is available at the current price.",
      "Empty shelves where the toilet paper used to be."),
    T("glut", "too much to sell",
      "When there is more of something than people want to buy at the current price.",
      "A warehouse full of unsold TVs after the holidays.",
      ["oversupply", "excess supply"]),
    T("elasticity", "how much buying changes when the price changes",
      "A measure of how sensitive people are to price. Elastic means a small price change causes a big change in buying. Inelastic means people keep buying regardless.",
      "Raise the price of one brand of soda and people switch (elastic). Raise the price of insulin and people still buy (inelastic).",
      ["price elasticity", "price elasticity of demand"]),
    T("elastic", "price-sensitive",
      "Describes something people buy a lot less of when its price rises, usually because there are easy alternatives.",
      "Raise the price of one brand of soda and people just switch brands."),
    T("inelastic", "not price-sensitive",
      "Describes something people keep buying about the same amount of even when the price rises, because they need it or have no alternative.",
      "Raise the price of insulin or gas and people still buy nearly as much."),
    T("opportunity cost", "what you give up by choosing one thing over another",
      "The value of the next best option you did not take.",
      "Spending Saturday at work means giving up the day at the beach."),
    T("scarcity", "not enough for everyone who wants it",
      "The basic problem that wants are unlimited but resources are not.",
      "There is only so much land, time, and money to go around."),
    T("marginal", "the effect of one more",
      "Relating to a small additional amount: the extra cost or benefit of one more unit.",
      "The marginal cost of one more pizza is just the extra dough and cheese.",
      ["marginal cost", "marginal benefit", "marginal utility", "marginal revenue", "at the margin"]),
    T("diminishing returns", "each extra bit helps less than the last",
      "The point where adding more of something gives smaller and smaller gains.",
      "The first slice of pizza is great; the fifth, not so much.",
      ["diminishing marginal returns", "diminishing marginal utility", "law of diminishing returns"]),
    T("economies of scale", "getting cheaper per unit as you make more",
      "Big producers can make each item more cheaply because fixed costs get spread over more units.",
      "A bakery making 1,000 loaves pays less per loaf than one making 10."),
    T("comparative advantage", "being relatively better at one thing",
      "The idea that everyone gains when each person or country focuses on what they do best relative to other tasks, then trades.",
      "A lawyer who types fast still hires a typist, because the lawyer's time is worth more in court."),
    T("competitive advantage", "an edge over rivals",
      "Something that lets a business beat its competitors, like lower costs or a better product.",
      "A cafe on the only corner with parking."),
    T("monopoly", "one seller controlling the market",
      "A market with a single seller and no real competition, which usually means higher prices.",
      "The only internet provider in town.",
      ["monopolist", "monopolistic", "monopolies"],
      plural="markets controlled by a single seller"),
    T("oligopoly", "a few big sellers controlling the market",
      "A market dominated by a handful of large companies.",
      "The few big airlines or phone carriers."),
    T("monopsony", "one buyer controlling the market",
      "A market with a single dominant buyer, which can push prices or wages down.",
      "A town where one factory is the only employer."),
    T("cartel", "rivals secretly agreeing to fix prices",
      "A group of competitors who agree to limit supply or set prices instead of competing.",
      "OPEC countries agreeing to pump less oil to keep prices high.",
      ["collusion", "price fixing", "price-fixing"]),
    T("perfect competition", "many small sellers with identical products",
      "A textbook market where no single seller can influence the price.",
      "Hundreds of farmers all selling the same wheat."),
    T("barriers to entry", "obstacles that keep new competitors out",
      "Things that make it hard for a new business to enter a market.",
      "The huge cost of building a chip factory.",
      ["barrier to entry", "entry barriers"]),
    T("antitrust", "laws against unfair market dominance",
      "Rules that stop companies from crushing competition or fixing prices.",
      "Regulators blocking a merger that would leave one grocery chain in a region.",
      ["anti-trust", "competition law"]),
    T("free market", "buying and selling without government interference",
      "An economy where prices are set by buyers and sellers, not by the government.",
      "A farmers' market where each stall sets its own prices.",
      ["free markets", "laissez-faire", "laissez faire", "market economy"]),
    T("invisible hand", "self-interest accidentally helping everyone",
      "Adam Smith's idea that people pursuing their own gain in a market end up benefiting society.",
      "The baker bakes bread to make money, and you get to eat."),
    T("rent-seeking", "profiting by gaming the rules rather than creating value",
      "Trying to get richer by lobbying, monopoly, or special treatment instead of making something useful.",
      "A company lobbying for a rule that bans its competitors.",
      ["rent seeking"]),
    T("economic rent", "extra profit beyond what is needed",
      "Payment above what would be necessary to keep a resource in use, often from owning something scarce.",
      "A landlord charging far more simply because the location is unique."),
    T("arbitrage", "buying cheap in one place and selling dear in another",
      "Profiting from a price difference for the same thing in two markets.",
      "Buying a sneaker for $100 at one store and selling it for $150 online.",
      ["arbitrageur"]),
    T("speculation", "betting on price moves",
      "Buying something not to use it but hoping to sell it later for more.",
      "Buying a condo to flip, not to live in.",
      ["speculative", "speculator", "speculators"]),
    T("bubble", "prices soaring far above what something is worth",
      "When prices rise way beyond any sensible value because everyone expects them to keep rising, until they crash.",
      "Tulip bulbs selling for the price of a house in 1637.",
      ["asset bubble", "housing bubble", "speculative bubble"],
      plural="prices soaring far above what things are worth"),
    T("commodity", "a basic raw good",
      "A standard product that is the same no matter who makes it, like oil or wheat.",
      "A barrel of oil is a barrel of oil, whoever pumped it.",
      ["commodities"],
      plural="basic raw goods"),
    T("consumer", "a shopper",
      "Anyone who buys goods or services for their own use.",
      "You, at the grocery store.",
      [],
      plural="shoppers"),
    T("household", "a family",
      "Economists' word for the people who live together and share money: a family, a couple, or one person living alone.",
      "Two roommates splitting rent count as one household.",
      ["households"],
      plural="families"),
    T("producer", "a business that makes things",
      "Anyone who creates goods or services to sell.",
      "A farmer, a factory, or a freelance designer.",
      ["producers"],
      plural="businesses that make things"),
    T("goods and services", "things you can buy",
      "Goods are physical things; services are work done for you.",
      "A phone is a good; a haircut is a service."),
    T("utility", "satisfaction",
      "The economist's word for the benefit or happiness you get from something.",
      "The enjoyment of a good meal."),
    T("welfare", "overall well-being",
      "In economics, how well off people are in total, not just the benefit program.",
      "Whether a policy leaves people better or worse off overall.",
      ["economic welfare", "social welfare"]),
    T("incentive", "a reason to act a certain way",
      "Something that motivates a person or business to make a choice.",
      "A bonus for hitting a sales target.",
      ["incentives", "incentivize", "incentivise"],
      plural="reasons to act a certain way"),
    T("rational actor", "someone who weighs costs and benefits",
      "The textbook assumption that people make decisions to get the most benefit for themselves.",
      "Choosing the cheaper of two identical products.",
      ["rational agent", "homo economicus"]),
    T("behavioral economics", "how people really decide, quirks and all",
      "The study of how real people make economic choices, including habits, biases, and mistakes.",
      "People buying more when a price ends in .99.",
      ["behavioural economics"]),
    T("zero-sum", "one person's gain is another's loss",
      "A situation where the total is fixed, so whatever one side wins the other loses.",
      "Splitting a single pie.",
      ["zero sum", "zero-sum game"]),
    T("tragedy of the commons", "everyone overusing a shared resource",
      "When individuals each take a bit more of a shared resource, it gets used up for everyone.",
      "Overfishing a lake until there are no fish left."),
    T("asymmetric information", "one side knowing more than the other",
      "When one party in a deal has information the other lacks.",
      "A used-car seller knowing the car has problems the buyer cannot see.",
      ["information asymmetry"]),
    T("adverse selection", "the wrong customers signing up",
      "When the people most likely to cost you are the ones most eager to buy.",
      "Only sick people buying health insurance, driving premiums up."),

    # -------------------------------------------------------- trade & global
    T("trade deficit", "the gap from buying more abroad than we sell",
      "When a country imports more than it exports.",
      "The US buying $100 of goods from abroad while selling $70 to other countries.",
      ["trade gap", "current account deficit"]),
    T("trade surplus", "the surplus from selling more abroad than we buy",
      "When a country exports more than it imports.",
      "Germany selling more cars abroad than it buys in foreign goods.",
      ["current account surplus"]),
    T("balance of trade", "the gap between exports and imports",
      "The difference between what a country sells abroad and what it buys from abroad.",
      "Sell $80 abroad, buy $100 from abroad: a $20 shortfall.",
      ["trade balance", "balance of payments", "current account"]),
    T("exports", "goods sold to other countries",
      "Things made at home and sold abroad.",
      "American soybeans shipped to China.",
      ["export"]),
    T("imports", "goods bought from other countries",
      "Things made abroad and bought at home.",
      "A phone assembled in Vietnam sold in Ohio.",
      ["import"]),
    T("protectionism", "shielding local businesses from foreign competition",
      "Using tariffs, quotas, or rules to make imports harder so local companies face less competition.",
      "Taxing foreign cars so people buy domestic ones.",
      ["protectionist"]),
    T("free trade", "buying and selling across borders without barriers",
      "Trade between countries without tariffs or quotas.",
      "Goods flowing between US states without any border tax.",
      ["free trade agreement", "trade liberalization", "trade liberalisation"]),
    T("quota", "a limit on how much can be imported",
      "A cap on the quantity of a product allowed into a country.",
      "Only 1 million foreign cars allowed in per year.",
      ["import quota", "quotas"],
      plural="limits on how much can be imported"),
    T("exchange rate", "what one currency is worth in another",
      "The price of one country's money in terms of another's.",
      "One dollar buys 0.90 euros today.",
      ["fx rate", "currency rate"]),
    T("devaluation", "making a currency worth less on purpose",
      "A government deliberately lowering the value of its currency against others.",
      "China letting the yuan weaken so its exports get cheaper.",
      ["devalue", "devalued"]),
    T("depreciation", "losing value over time",
      "A currency or asset becoming worth less. For currencies, it means one unit buys less foreign money.",
      "The pound falling from $1.40 to $1.20, or a car losing value each year."),
    T("appreciation", "gaining value over time",
      "A currency or asset becoming worth more.",
      "The dollar rising so your vacation in Europe gets cheaper."),
    T("strong dollar", "a dollar that buys a lot of foreign currency",
      "When the dollar is worth more against other currencies, making imports and foreign travel cheaper but exports harder to sell.",
      "Your trip to Paris costs less, but US farmers sell less abroad."),
    T("weak dollar", "a dollar that buys less foreign currency",
      "When the dollar is worth less against other currencies, making imports pricier but exports easier to sell.",
      "Foreign goods cost more, but foreign buyers snap up US products."),
    T("globalization", "countries becoming more economically connected",
      "The growing flow of goods, money, people, and ideas across borders.",
      "A phone designed in California, built in China, sold in Brazil.",
      ["globalisation"]),
    T("offshoring", "moving work to another country",
      "Relocating production or jobs abroad, usually to cut costs.",
      "A call center moving from Ohio to the Philippines.",
      ["offshore", "outsourcing"]),
    T("emerging markets", "fast-growing poorer countries",
      "Developing countries whose economies are growing quickly but are still catching up.",
      "India, Brazil, Indonesia.",
      ["emerging economies", "developing countries", "developing economies"]),
    T("sanctions", "penalties on a country's trade or finances",
      "Restrictions one country places on another's trade or banking to punish or pressure it.",
      "Banning imports of Russian oil.",
      ["economic sanctions", "sanction"]),
    T("foreign direct investment", "foreign companies building or buying businesses here",
      "Money from abroad used to start or buy businesses in a country.",
      "A Japanese carmaker building a plant in Tennessee.",
      ["fdi"]),
    T("capital flight", "money rushing out of a country",
      "Investors quickly moving their money abroad, usually out of fear.",
      "Wealthy people wiring savings overseas when a crisis hits."),
    T("supply chain", "the chain of steps that gets a product to you",
      "All the companies and steps involved in making and delivering a product.",
      "Cotton farm to fabric mill to factory to store to your closet.",
      ["supply chains", "supply chain disruption"],
      plural="the chains of steps that get products to you"),

    # ------------------------------------------------------- finance & bonds
    T("bond", "an IOU that pays interest",
      "A loan you make to a government or company. They pay you interest and return the money at a set date.",
      "Lend the government $1,000 for 10 years and collect $40 a year.",
      ["bonds", "treasury bonds", "treasuries", "treasury", "gilts", "government bonds", "corporate bonds", "fixed income"],
      plural="IOUs that pay interest"),
    T("yield", "the interest return",
      "The yearly income from a bond or investment as a percentage of its price.",
      "A $1,000 bond paying $50 a year has a 5% yield.",
      ["bond yield", "bond yields", "yields", "treasury yield", "10-year yield"],
      plural="interest returns"),
    T("yield curve", "the line of interest rates from short to long loans",
      "A chart showing interest rates for loans of different lengths. Normally longer loans pay more.",
      "A 1-year bond at 4% and a 10-year bond at 5% make an upward-sloping curve."),
    T("inverted yield curve", "short-term loans paying more than long-term ones",
      "When short-term interest rates are higher than long-term ones, an unusual situation that often comes before a recession.",
      "A 2-year bond paying more than a 10-year bond."),
    T("equity", "ownership in a company",
      "A share of ownership, or the value of what you own minus what you owe on it.",
      "Owning shares in Apple, or the part of your house you have actually paid off.",
      ["equities", "stocks", "shares"],
      plural="shares of ownership in companies"),
    T("dividend", "a company's cash payout to shareholders",
      "A slice of profits a company pays to the people who own its shares.",
      "Getting $2 per share every quarter.",
      ["dividends"],
      plural="cash payouts to a company's owners"),
    T("asset", "something you own that has value",
      "Anything of value that can be owned, like cash, a house, or shares.",
      "Your car, savings account, and retirement fund.",
      ["assets", "asset prices", "financial assets"],
      plural="things you own that have value"),
    T("liability", "something you owe",
      "A debt or obligation to pay.",
      "Your mortgage and credit card balance.",
      ["liabilities"],
      plural="things you owe"),
    T("portfolio", "the collection of investments someone owns",
      "All of an investor's holdings, taken together.",
      "Your mix of stocks, bonds, and savings."),
    T("diversification", "not putting all your eggs in one basket",
      "Spreading investments across different things so one bad bet cannot sink you.",
      "Owning 50 different stocks instead of one.",
      ["diversify", "diversified"]),
    T("volatility", "how wildly prices swing",
      "How much and how fast a price moves up and down.",
      "A stock that jumps 10% one day and drops 8% the next.",
      ["volatile"]),
    T("bull market", "a period of rising prices",
      "A stretch when stock or asset prices keep going up and investors are optimistic.",
      "Stocks climbing steadily for years.",
      ["bullish"]),
    T("bear market", "a period of falling prices",
      "A stretch when prices drop 20% or more from their high and investors are gloomy.",
      "Stocks sliding for months in 2008.",
      ["bearish"]),
    T("correction", "a modest price drop after a run-up",
      "A fall of roughly 10% from a recent high, less severe than a bear market.",
      "Stocks slipping 10% after a big rally.",
      ["market correction"]),
    T("crash", "a sudden, steep price collapse",
      "A very fast, very large drop in prices.",
      "Stocks losing 20% in a single day in 1987.",
      ["market crash", "stock market crash"]),
    T("rally", "a quick rise in prices",
      "A period of rapidly rising prices.",
      "Stocks jumping 5% in a week after good news."),
    T("hedge", "protection against a loss",
      "An investment made to offset the risk of another one.",
      "Buying insurance on your house.",
      ["hedging", "hedged"],
      plural="protections against losses"),
    T("derivative", "a bet whose value depends on something else",
      "A financial contract whose value comes from an underlying asset like a stock, a currency, or oil.",
      "A contract that pays out if oil goes above $90 a barrel.",
      ["derivatives"],
      plural="bets whose value depends on something else"),
    T("securities", "tradeable financial products",
      "Things like stocks and bonds that can be bought and sold.",
      "Anything you might see in a brokerage account."),
    T("mortgage-backed securities", "bundles of home loans sold to investors",
      "Home loans packaged together and sold as an investment. Investors get the monthly payments.",
      "Thousands of mortgages bundled into one product, famous from 2008.",
      ["mbs", "mortgage backed securities"]),
    T("securitization", "bundling loans to sell as investments",
      "Turning a pool of loans into tradeable securities.",
      "A bank packaging 5,000 car loans and selling them to investors.",
      ["securitisation", "securitized", "securitised"]),
    T("credit rating", "a grade for how safe a borrower is",
      "A score showing how likely a borrower is to pay back its debts.",
      "AAA is very safe; junk means risky.",
      ["credit ratings", "credit score", "rating agency", "rating agencies"],
      plural="grades for how safe borrowers are"),
    T("risk premium", "extra return for taking extra risk",
      "The additional return investors demand for holding something riskier than a safe bet.",
      "A shaky company must pay 9% on its bonds while the government pays 4%.",
      ["risk premia"]),
    T("capital gains", "profit from selling something for more than you paid",
      "The gain when you sell an asset at a higher price than you bought it.",
      "Buying shares at $50 and selling at $80.",
      ["capital gain", "capital gains tax"]),
    T("return on investment", "what you got back compared to what you put in",
      "The profit from an investment as a percentage of its cost.",
      "Invest $100, end up with $110: a 10% return.",
      ["roi"]),
    T("compound interest", "interest earning interest",
      "When the interest you earn is added to your balance, so the next round of interest is bigger.",
      "$1,000 at 10% becomes $1,100, then $1,210, then $1,331.",
      ["compounding"]),
    T("principal", "the original amount borrowed or invested",
      "The base sum of a loan or investment, not counting interest.",
      "On a $200k mortgage, $200k is the principal."),
    T("amortization", "paying off a loan bit by bit",
      "Spreading loan repayment over regular installments that cover both interest and the amount borrowed.",
      "A 30-year mortgage paid in 360 monthly chunks.",
      ["amortisation", "amortized", "amortised"]),
    T("collateral", "something you pledge to lose if you do not repay",
      "An asset the lender can take if you fail to pay back a loan.",
      "Your house on a mortgage, your car on a car loan."),
    T("net worth", "what you own minus what you owe",
      "Total assets minus total debts.",
      "A $300k house and $50k savings minus a $200k mortgage is $150k net worth."),
    T("cash flow", "money coming in versus going out",
      "The movement of money into and out of a business or household over time.",
      "A shop taking in $10k a month and paying out $8k has positive cash flow."),
    T("revenue", "total money taken in",
      "All the money a business receives from sales before any costs are subtracted.",
      "A lemonade stand selling 100 cups at $1 has $100 revenue.",
      ["revenues", "turnover", "top line"]),
    T("profit", "money left after costs",
      "What is left from revenue after paying all expenses.",
      "$100 in lemonade sales minus $30 for lemons and sugar is $70 profit.",
      ["profits", "net income", "earnings", "bottom line", "profit margin", "margins"],
      plural="money left after costs"),
    T("overhead", "ongoing costs of running a business",
      "Costs that must be paid regardless of how much is sold.",
      "Rent, insurance, and electricity for a store.",
      ["fixed costs", "fixed cost"]),
    T("variable costs", "costs that rise as you make more",
      "Expenses that go up with each extra unit produced.",
      "Flour and eggs for each extra cake.",
      ["variable cost"]),
    T("depreciation expense", "the cost of things wearing out",
      "Spreading the cost of a machine or building over the years it is used.",
      "A $10k van written off at $2k a year for five years."),
    T("market capitalization", "what a whole company is worth on the stock market",
      "The total value of all a company's shares.",
      "10 million shares at $50 each means a $500 million company.",
      ["market cap"]),
    T("ipo", "a company selling shares to the public for the first time",
      "An initial public offering: the first time a company's shares are sold on a stock exchange.",
      "A startup listing on the Nasdaq.",
      ["initial public offering"]),
    T("venture capital", "money invested in risky young companies",
      "Funding given to startups in exchange for ownership, in hope of a big payoff.",
      "A fund putting $5M into an app in exchange for 20% of it.",
      ["vc"]),
    T("private equity", "investors buying whole companies",
      "Funds that buy companies outright, often with borrowed money, to improve and resell them.",
      "A fund buying a chain of dental clinics."),
    T("hedge fund", "a lightly regulated investment fund for the wealthy",
      "An investment pool that uses aggressive strategies and is open only to rich or institutional investors.",
      "A fund betting that a company's stock will fall.",
      ["hedge funds"]),
    T("index fund", "a fund that simply owns the whole market",
      "A low-cost fund that holds every stock in an index like the S&P 500 rather than picking winners.",
      "One purchase that gives you a sliver of 500 big companies."),
    T("s&p 500", "the 500 biggest US companies' stock index",
      "An index tracking 500 large US companies, used as shorthand for 'the stock market'.",
      "When the news says 'stocks rose', it usually means this.",
      ["s&p", "dow jones", "the dow", "nasdaq", "stock index", "stock market index"]),
    T("basis points", "hundredths of a percent",
      "One basis point is 0.01 percentage points. 100 basis points equals 1 percentage point.",
      "A rate going from 5.00% to 5.25% rose 25 basis points.",
      ["basis point", "bps"]),

    # ------------------------------------------------- housing & households
    T("mortgage", "a home loan",
      "A loan used to buy a house, with the house as security.",
      "Borrowing $300k to buy a home and paying it back over 30 years.",
      ["mortgages", "mortgage rates", "mortgage rate"],
      plural="home loans"),
    T("foreclosure", "the bank taking your house for missed payments",
      "When a lender seizes a home because the owner stopped paying the mortgage.",
      "A family losing their house after a year of missed payments.",
      ["foreclosures", "foreclose"]),
    T("negative equity", "owing more on your home than it is worth",
      "When your mortgage balance is bigger than your home's market value.",
      "Owing $300k on a house now worth $250k.",
      ["underwater mortgage", "underwater"]),
    T("household debt", "what families owe",
      "All the debt held by households: mortgages, car loans, credit cards, student loans.",
      "A family's combined mortgage, car payment, and credit card balance.",
      ["consumer debt"]),
    T("savings rate", "the share of income people save",
      "The percentage of take-home pay that households put away instead of spending.",
      "Earning $4,000 a month and saving $400 is a 10% savings rate.",
      ["personal savings rate", "household savings"]),
    T("consumer confidence", "how optimistic people feel about money",
      "A survey measure of how people feel about the economy and their own finances, which predicts spending.",
      "People planning vacations and big purchases when they feel secure.",
      ["consumer sentiment"]),
    T("wealth effect", "spending more because you feel richer",
      "When rising home or stock values make people spend more, even if their income has not changed.",
      "Buying a boat because your house 'went up' $100k on paper."),
    T("wealth inequality", "the gap between what the rich and poor own",
      "How unevenly wealth is spread across a population.",
      "The top 1% owning a third of everything.",
      ["income inequality", "inequality", "wealth gap", "income gap"]),
    T("gini coefficient", "a 0-to-1 score for inequality",
      "A number measuring how unequal incomes are: 0 means everyone earns the same, 1 means one person has everything.",
      "A score of 0.25 is fairly equal; 0.50 is very unequal.",
      ["gini index", "gini"]),
    T("poverty line", "the income level below which you count as poor",
      "The minimum income the government says a household needs to cover basics.",
      "About $31,000 for a family of four in the US.",
      ["poverty threshold", "poverty rate"]),
    T("median income", "the middle income",
      "The income level where half of people earn more and half earn less. Less skewed by billionaires than the average.",
      "If five people earn $20k, $30k, $40k, $50k, and $5M, the median is $40k.",
      ["median household income", "median wage"]),
    T("standard of living", "how comfortably people live",
      "The level of wealth, comfort, and goods available to people.",
      "Whether a typical family can afford a car, healthcare, and a vacation.",
      ["living standards"]),
    T("universal basic income", "a regular cash payment to everyone",
      "A policy of giving every citizen a set amount of money regularly, no strings attached.",
      "Every adult receiving $1,000 a month from the government.",
      ["ubi", "basic income"]),

    # ------------------------------------------------------- theory & schools
    T("keynesian", "favoring government spending to steady the economy",
      "An approach, from economist John Maynard Keynes, that says governments should spend more in slumps to keep demand up.",
      "Building roads during a recession to keep people employed.",
      ["keynesianism", "keynesian economics"]),
    T("monetarism", "focusing on the money supply to control prices",
      "The view that inflation mainly comes from how much money is in circulation, so controlling the money supply is key.",
      "Milton Friedman's line: inflation is always and everywhere a monetary phenomenon.",
      ["monetarist"]),
    T("supply-side economics", "boosting the economy by cutting taxes and rules",
      "The idea that lower taxes and fewer regulations encourage businesses to produce more, which grows the economy.",
      "Cutting corporate taxes so companies invest more.",
      ["supply side economics", "supply-side", "trickle-down", "trickle down economics", "reaganomics"]),
    T("austrian economics", "a school that distrusts central planning and central banks",
      "A school of thought that emphasizes free markets and sees government and central-bank meddling as the source of booms and busts.",
      "Blaming low interest rates for a housing bubble.",
      ["austrian school"]),
    T("neoliberalism", "free markets, free trade, and a smaller government",
      "A broad label for policies favoring open markets, privatization, and less government involvement in the economy.",
      "Selling off state industries and cutting trade barriers in the 1980s and 90s.",
      ["neoliberal"]),
    T("macroeconomics", "the study of the whole economy",
      "The big-picture branch of economics: growth, inflation, unemployment, and government policy.",
      "Asking why the whole country is in a recession.",
      ["macroeconomic"]),
    T("microeconomics", "the study of individual choices and markets",
      "The small-picture branch: how people, households, and businesses make decisions and how single markets work.",
      "Asking why coffee costs $5 at this cafe.",
      ["microeconomic"]),
    T("ceteris paribus", "all else being equal",
      "A Latin phrase meaning 'holding everything else the same', used to isolate one cause.",
      "If the price of apples rises, ceteris paribus, people buy fewer apples.",
      ["all other things being equal", "other things equal"]),
    T("phillips curve", "the trade-off between joblessness and rising prices",
      "The observation that when unemployment is low, inflation tends to be high, and vice versa.",
      "A hot job market pushing wages, and then prices, up."),
    T("natural rate of unemployment", "the lowest unemployment can go without pushing prices up",
      "The level of unemployment that exists even in a healthy economy, from people moving between jobs.",
      "Around 4% in the US.",
      ["nairu"]),
    T("multiplier effect", "knock-on effect",
      "When new spending gets re-spent again and again, boosting the economy by more than the original amount.",
      "A $1,000 stimulus check pays a plumber, who pays a grocer, who pays a farmer.",
      ["fiscal multiplier"]),
    T("velocity of money", "how fast money changes hands",
      "How many times a dollar is spent in a year.",
      "The same $20 bill paying for lunch, then a haircut, then groceries in one week.",
      ["money velocity"]),
    T("liquidity trap", "situation where cheap money stops working",
      "A situation where interest rates are near zero but people still will not borrow or spend, so cuts have no effect.",
      "Japan in the 1990s: free money, no takers."),
    T("zero lower bound", "interest rates cannot go below zero",
      "The problem that a central bank cannot cut rates much below zero, limiting its options in a deep slump.",
      "Rates at 0% with nowhere left to cut.",
      ["zlb"]),
    T("inflation targeting", "aiming for a set rate of price increases",
      "A central bank publicly aiming for a specific inflation rate, usually 2%.",
      "The Fed trying to keep prices rising about 2% a year.",
      ["inflation target", "2% target"]),
    T("forward guidance", "the central bank hinting at its future moves",
      "A central bank telling the public what it plans to do with interest rates so people can plan.",
      "The Fed saying it expects to hold rates steady through next year."),
    T("inflation expectations", "what people think prices will do",
      "How much people expect prices to rise, which shapes their wage demands and spending.",
      "Workers asking for bigger raises because they expect prices to jump."),
    T("wage-price spiral", "wages and prices chasing each other upward",
      "When rising prices lead to higher wage demands, which raise costs and prices further.",
      "Workers get 8% raises, shops raise prices 8%, workers ask for another raise.",
      ["wage price spiral"]),
    T("demand-pull inflation", "prices rising because people want to buy more than is available",
      "Inflation caused by too much spending chasing too few goods.",
      "Everyone gets a bonus and rushes to buy the same limited stock of cars.",
      ["demand pull inflation"]),
    T("cost-push inflation", "prices rising because making things got more expensive",
      "Inflation caused by higher costs, like wages or raw materials, being passed on to customers.",
      "Oil prices spike, so shipping and then groceries cost more.",
      ["cost push inflation"]),
    T("creative destruction", "new industries wiping out old ones",
      "The process where innovation destroys old businesses but creates better ones.",
      "Streaming killing video rental stores."),
    T("nudge", "a gentle push toward a better choice",
      "Designing choices so people are steered toward a good option without forcing them.",
      "Making retirement saving the default so people have to opt out.",
      ["nudges", "choice architecture"]),
    T("sunk cost", "money already spent that you cannot get back",
      "A past cost that should not affect a decision, because it is gone either way.",
      "Finishing a bad movie because you paid for the ticket.",
      ["sunk costs", "sunk cost fallacy"]),
    T("game theory", "the study of strategic decisions",
      "The study of how people make choices when the outcome depends on what others do.",
      "Deciding whether to cut prices knowing your rival might too."),
    T("prisoner's dilemma", "a situation where selfish choices leave everyone worse off",
      "A classic game where two people each do better by betraying the other, yet both lose if both betray.",
      "Two rival stores both slashing prices and both losing money.",
      ["prisoners dilemma"]),
    T("pareto efficiency", "no one can be made better off without hurting someone else",
      "A situation where resources are allocated so that improving one person's lot means worsening another's.",
      "A pie fully divided: giving anyone more means taking from someone.",
      ["pareto efficient", "pareto optimal", "pareto optimality"]),
    T("dead weight loss", "value lost when a market is distorted",
      "The benefit that disappears when a tax, price control, or monopoly stops trades that would have helped both sides.",
      "A tax so high that some people stop buying and the seller stops selling, so no one gets that value.",
      ["deadweight loss"]),
    T("consumer surplus", "the deal you got below what you would have paid",
      "The gap between what you were willing to pay and what you actually paid.",
      "Willing to pay $50 for a jacket, finding it for $30: $20 of surplus."),
    T("producer surplus", "the extra a seller gets above their minimum price",
      "The gap between the lowest price a seller would accept and the price they actually got.",
      "Willing to sell for $20, selling for $30: $10 of surplus."),

    # ------------------------------------------------------ misc common terms
    T("indicator", "a measurement that signals how the economy is doing",
      "Any statistic used to judge the health of the economy.",
      "Unemployment, inflation, and GDP growth.",
      ["economic indicator", "economic indicators", "leading indicator", "lagging indicator", "indicators"],
      plural="measurements that signal how the economy is doing"),
    T("headwinds", "things slowing the economy down",
      "Obstacles that make growth harder.",
      "High interest rates and expensive fuel.",
      ["headwind"]),
    T("tailwinds", "things helping the economy along",
      "Favorable conditions that make growth easier.",
      "Cheap energy and strong consumer spending.",
      ["tailwind"]),
    T("overheating", "the economy growing too fast to be healthy",
      "When demand is so strong that prices start rising too quickly.",
      "A job market so hot that employers cannot find workers and keep raising wages.",
      ["overheated", "overheat"]),
    T("shock", "a sudden unexpected event that hits the economy",
      "An unforeseen jolt, like a war or pandemic, that disrupts normal activity.",
      "Oil prices doubling overnight after a conflict.",
      ["economic shock", "supply shock", "demand shock", "external shock"],
      plural="sudden unexpected events that hit the economy"),
    T("bottleneck", "a choke point slowing everything down",
      "One stage in a process that cannot keep up, holding up everything behind it.",
      "A single clogged port delaying goods across the country.",
      ["bottlenecks"],
      plural="choke points slowing everything down"),
    T("dovish", "rate-cut-leaning",
      "Describes a central banker who favors keeping rates low to support jobs, even if prices rise a bit.",
      "A Fed official saying growth matters more than inflation right now.",
      ["dove", "doves"]),
    T("hawkish", "rate-hike-leaning",
      "Describes a central banker who favors raising rates to fight inflation, even if it slows growth.",
      "A Fed official pushing for another rate hike.",
      ["hawk", "hawks"]),
    T("tightening", "making borrowing harder or costlier",
      "Raising interest rates or reducing the money supply to slow the economy.",
      "The Fed raising rates three times in a year.",
      ["tighten", "tighter"]),
    T("loosening", "making borrowing easier or cheaper",
      "Cutting interest rates or adding money to speed up the economy.",
      "The Fed cutting rates to help a weak job market.",
      ["loosen", "looser", "accommodative"]),
    T("stagnation", "an economy stuck with no growth",
      "A long stretch with little or no economic growth.",
      "Years of the economy barely budging.",
      ["stagnant", "secular stagnation"]),
    T("boom", "a period of very fast growth",
      "A time of rapid expansion, high spending, and low unemployment.",
      "The late 1990s tech boom.",
      ["booming"]),
    T("bust", "a sharp collapse after a boom",
      "A sudden downturn that follows a boom.",
      "The dot-com bust of 2000.",
      ["boom and bust", "boom-bust"]),
    T("stakeholder", "anyone affected by a decision",
      "A person or group with an interest in how something turns out.",
      "A company's workers, customers, and neighbors, not just its owners.",
      ["stakeholders"],
      plural="everyone affected by a decision"),
    T("shareholder", "someone who owns part of a company",
      "A person or fund that owns shares in a company.",
      "Anyone with Apple stock in their retirement account.",
      ["shareholders", "stockholders", "stockholder"],
      plural="people who own part of a company"),
    T("monetize", "turn into money",
      "To find a way to make money from something.",
      "A YouTuber running ads on their videos.",
      ["monetise", "monetization", "monetisation"]),
    T("capital expenditure", "spending on big long-term items",
      "Money a business spends on buildings, equipment, and other things it will use for years.",
      "A trucking company buying ten new trucks.",
      ["capex"]),
    T("operating expenses", "day-to-day running costs",
      "The regular costs of keeping a business going.",
      "Salaries, rent, and utilities.",
      ["opex"]),
    T("gross margin", "the share of sales left after making the product",
      "Revenue minus the direct cost of making what was sold, as a percentage of revenue.",
      "Sell a shirt for $20 that cost $8 to make: 60% gross margin."),
    T("merger", "two companies combining into one",
      "When two businesses join together.",
      "Two regional banks becoming one.",
      ["mergers", "acquisition", "acquisitions", "m&a", "takeover"],
      plural="companies combining"),
    T("cryptocurrency", "digital money not run by any government",
      "Money that exists only online and is tracked by a shared ledger rather than a bank.",
      "Bitcoin or Ethereum.",
      ["crypto", "bitcoin", "digital currency"]),
    T("fiat money", "money that is valuable because the government says so",
      "Currency with no gold or other backing, whose value rests on trust in the government issuing it.",
      "The US dollar since 1971.",
      ["fiat currency", "fiat"]),
    T("gold standard", "money backed by gold",
      "A system where currency can be exchanged for a fixed amount of gold.",
      "Trading a $20 bill for an ounce of gold at the bank, as in the 1800s."),
    T("gig economy", "short-term freelance work through apps",
      "An economy where many people work temporary jobs, often via apps, rather than as employees.",
      "Driving for Uber or delivering for DoorDash."),
    T("circular economy", "reusing and recycling instead of throwing away",
      "An economic model that keeps materials in use rather than making, using, and discarding.",
      "A company taking back old phones to recover the metals."),
    T("black market", "illegal buying and selling",
      "Trade that happens outside the law, often to avoid taxes or bans.",
      "Selling cigarettes without paying tax.",
      ["informal economy", "shadow economy", "underground economy", "grey market", "gray market"]),
    T("remittances", "money migrants send home",
      "Money that workers abroad send back to family in their home country.",
      "A nurse in London wiring money to her parents in Manila.",
      ["remittance"]),
    T("brain drain", "skilled people leaving a country",
      "When educated workers emigrate, taking their skills elsewhere.",
      "Doctors trained in one country moving abroad for better pay."),
    T("seasonally adjusted", "smoothed to remove predictable seasonal swings",
      "A statistic corrected for regular yearly patterns, like holiday hiring, so months can be compared fairly.",
      "Retail sales look flat once the December shopping bump is stripped out.",
      ["seasonal adjustment"]),
    T("annualized", "scaled up to a full-year rate",
      "A short-period number stretched out to show what it would be over a whole year.",
      "Growth of 0.5% in one quarter is about 2% annualized.",
      ["annualised", "annualized rate"]),
    T("year-over-year", "compared to the same time last year",
      "A change measured against the same month or quarter a year earlier.",
      "Prices in March versus prices last March.",
      ["year on year", "yoy", "y/y"]),
    T("quarter-over-quarter", "compared to the previous three months",
      "A change measured against the previous quarter.",
      "Sales this spring versus this winter.",
      ["quarter on quarter", "qoq", "q/q"]),
    T("quarter", "a three-month period",
      "One quarter of a year, the standard unit for reporting economic and business results.",
      "January through March is the first quarter.",
      ["quarterly", "q1", "q2", "q3", "q4"]),
    T("fiscal year", "a company's or government's 12-month accounting year",
      "A 12-month period used for budgeting, which may not match the calendar year.",
      "The US government's year runs October through September."),
    T("percentage point", "a difference of one whole percent",
      "The simple difference between two percentages, as opposed to a percentage change.",
      "Going from 2% to 3% is a rise of 1 percentage point, but a 50% increase.",
      ["percentage points"],
      keep=True),
]

# ------------------------------------------------------------------------
# General wordiness that is not economics but often appears alongside it.
# Applied only in the Econ -> Plain direction.
SIMPLIFICATIONS = {
    "in order to": "to",
    "with regard to": "about",
    "with respect to": "about",
    "in the event that": "if",
    "in light of": "because of",
    "in excess of": "more than",
    "prior to": "before",
    "subsequent to": "after",
    "in the absence of": "without",
    "for the purpose of": "to",
    "at this point in time": "now",
    "a significant proportion of": "many",
    "the majority of": "most",
    "a number of": "some",
    "notwithstanding": "despite",
    "utilize": "use",
    "utilise": "use",
    "utilization": "use",
    "approximately": "about",
    "individuals": "people",
    "purchase": "buy",
    "purchasing": "buying",
    "purchased": "bought",
    "commence": "start",
    "sufficient": "enough",
    "insufficient": "not enough",
    "facilitate": "help",
    "exacerbate": "make worse",
    "mitigate": "reduce",
    "ameliorate": "improve",
    "attenuate": "weaken",
    "curtail": "cut back",
    "constrain": "limit",
    "endeavor": "try",
    "endeavour": "try",
    "implement": "carry out",
    "initiate": "start",
    "terminate": "end",
    "additional": "extra",
    "numerous": "many",
    "subsequently": "later",
    "consequently": "so",
    "therefore": "so",
    "nevertheless": "still",
    "furthermore": "also",
    "moreover": "also",
    "however": "but",
    "remuneration": "pay",
    "compensation": "pay",
    "expenditure": "spending",
    "expenditures": "spending",
    "revenue-generating": "money-making",
    "ascertain": "find out",
    "demonstrate": "show",
    "indicate": "show",
    "trajectory": "path",
    "robust": "strong",
    "resilient": "able to withstand hard times",
    "attributable to": "caused by",
    "in conjunction with": "with",
    "on a monthly basis": "every month",
    "on an annual basis": "every year",
    "adversely affect": "hurt",
    "adversely impact": "hurt",
    "negatively impact": "hurt",
    "optimal": "best",
    "suboptimal": "not the best",
    "heterogeneous": "varied",
    "homogeneous": "all the same",
    "exogenous": "from outside",
    "endogenous": "from inside",
    "empirical": "based on real data",
    "counterfactual": "what would have happened otherwise",
    "ex ante": "beforehand",
    "ex post": "afterwards",
    "de facto": "in practice",
    "de jure": "by law",
    "vis-a-vis": "compared with",
    "vis-à-vis": "compared with",
    "per annum": "per year",
}
